1.Write a Pandas program to compare the elements of two Pandas series. 
Sample Series [4,65,436,3,9], [7,0,3,897,9]

In [1]:

import pandas as pd

series1 = pd.Series([4, 65, 436, 3, 9])
series2 = pd.Series([7, 0, 3, 897, 9])

compare= series1 == series2
print(compare)

0    False
1    False
2    False
3    False
4     True
dtype: bool

2.Write a Pandas program to add, subtract, multiply and divide two Pandas series. 
Sample Series: [2,4,6,8,14], [1,3,5,7,9]

In [2]:

import pandas as pd

series1 = pd.Series([2, 4, 6, 8, 14])
series2 = pd.Series([1, 3, 5, 7, 9])

addition = series1 + series2
subtraction = series1 - series2
multiplication = series1 * series2
division = series1 / series2

print("Addition:")
print(addition)
print("Subtraction:")
print(subtraction)
print("Multiplication:")
print(multiplication)
print("Division:")
print(division)

Addition:
0     3
1     7
2    11
3    15
4    23
dtype: int64
Subtraction:
0    1
1    1
2    1
3    1
4    5
dtype: int64
Multiplication:
0      2
1     12
2     30
3     56
4    126
dtype: int64
Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

# 3.Write a Pandas program to convert a dictionary to a Pandas series. 
# Sample dictionary: dictionary1 = {‘Josh’: 24, ‘Sam’: 36, ‘Peace’: 19, ‘Charles’: 65, ‘Tom’: 44}

In [3]:

import pandas as pd

dict = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}
series = pd.Series(dict)
print(series)

Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

In [4]:
#4.Write a Pandas program to convert a given series to an array.
#Sample series: [‘Love’, 800, ‘Joy’, 789.9, ‘Peace’, True]
import pandas as pd
import numpy as np

series = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])
array = np.array(series)
print(array)

['Love' 800 'Joy' 789.9 'Peace' True]

In [5]:
#5.Write a Pandas program to display the most frequent value in the given series and replace everything else as ‘Other’ in the series. 
#(Use the ‘HomeTeamGoals’ column in the dataset provided)
import pandas as pd

df = pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')  

# Find the most frequent value
most_frequent_value = df['HomeTeamGoals'].mode()[0]

# Replace everything else as 'Other'
df['HomeTeamGoals'] = df['HomeTeamGoals'].apply(lambda x: most_frequent_value if x == most_frequent_value else 'Other')

print(df['HomeTeamGoals'])

0        1.0
1      Other
2      Other
3      Other
4        1.0
       ...
617    Other
618      1.0
619    Other
620    Other
621    Other
Name: HomeTeamGoals, Length: 622, dtype: object

In [6]:
#EXERCISE 2
#DATAFRAMES
#1.Write a Pandas program to read the given csv file.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="darkgrid", rc={"axes.facecolor": "white"})

# Rest of your code
pd.options.display.max_columns = 50

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')

In [7]:
#2.Write a Pandas program to get the first 7 rows of your data frame.
df.head(7)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0

In [8]:
#3.Write a Pandas program to select the ‘HomeTeam’, ‘AwayTeam’, ‘HomeTeamGoals’ and ‘AwayTeamGoals’ columns from your data frame.
selected_columns = df[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]
print(selected_columns)

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

In [9]:
#4.Write a Pandas program to select the rows where Egypt appears.
egypt_rows = df[df['HomeTeam'].str.contains('Egypt') | df['AwayTeam'].str.contains('Egypt')]
print(egypt_rows)

     Year                         Date   Time  HomeTeam       AwayTeam  \
0    1957                     10-Feb-57    NaN   Sudan           Egypt
2    1957                     16-Feb-57    NaN   Egypt        Ethiopia
3    1959                     22-May-59    NaN    Egypt       Ethiopia
5    1959                     29-May-59    NaN    Egypt          Sudan
7    1962                     18-Jan-62    NaN    Egypt         Uganda
..    ...                           ...    ...      ...            ...
569  2017  5 February 2017 (2017-02-05)  20:00   Egypt        Cameroon
570  2019     21 June 2019 (2019-06-21)  22:00   Egypt        Zimbabwe
573  2019     26 June 2019 (2019-06-26)  22:00   Egypt        DR Congo
574  2019     30 June 2019 (2019-06-30)  21:00  Uganda           Egypt
609  2019      6 July 2019 (2019-07-06)  21:00   Egypt    South Africa

     HomeTeamGoals  AwayTeamGoals             Stage SpecialWinConditions  \
0              1.0            2.0        Semifinals                  NaN
2              4.0            0.0             Final                  NaN
3              4.0            0.0  Final Tournament                  NaN
5              2.0            1.0  Final Tournament                  NaN
7              2.0            1.0        Semifinals                  NaN
..             ...            ...               ...                  ...
569            1.0            2.0             Final                  NaN
570            1.0            0.0           Group A                  NaN
573            2.0            0.0           Group A                  NaN
574            0.0            2.0           Group A                  NaN
609            0.0            1.0       Round of 16                  NaN

                         Stadium          City  Attendance
0              Municipal Stadium      Khartoum     30000.0
2              Municipal Stadium      Khartoum     30000.0
3          Prince Farouk Stadium         Cairo     30000.0
5          Prince Farouk Stadium         Cairo     30000.0
7         Hailé Sélassié Stadium   Addis Ababa     30000.0
..                           ...           ...         ...
569            Stade de l'Amitié    Libreville         NaN
570  Cairo International Stadium         Cairo     73299.0
573  Cairo International Stadium         Cairo     74219.0
574  Cairo International Stadium         Cairo     74566.0
609  Cairo International Stadium         Cairo     75000.0

[95 rows x 12 columns]

In [10]:
#5.Write a Pandas program to count the number of rows and columns of your data frame.
num_rows, num_cols = df.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

Number of rows: 622
Number of columns: 12

In [11]:
#6.Write a Pandas program to select the rows where the ‘Attendance’ is missing.
missing_attendance = df[df['Attendance'].isnull()]
print(missing_attendance)

     Year                         Date   Time        HomeTeam       AwayTeam  \
1    1957                     10-Feb-57    NaN      Ethiopia    South Africa
8    1962                     20-Jan-62    NaN       Tunisia          Uganda
9    1962                     21-Jan-62    NaN      Ethiopia           Egypt
10   1963                     24-Nov-63    NaN         Ghana         Tunisia
11   1963                     26-Nov-63    NaN         Ghana        Ethiopia
..    ...                           ...    ...            ...            ...
565  2017  29 January 2017 (2017-01-29)  20:00         Egypt         Morocco
566  2017  1 February 2017 (2017-02-01)  20:00  Burkina Faso           Egypt
567  2017  2 February 2017 (2017-02-02)  20:00      Cameroon           Ghana
568  2017  4 February 2017 (2017-02-04)  20:00  Burkina Faso           Ghana
569  2017  5 February 2017 (2017-02-05)  20:00         Egypt        Cameroon

     HomeTeamGoals  AwayTeamGoals                 Stage  \
1              NaN            NaN            Semifinals
8              3.0            0.0     Third place match
9              4.0            2.0                 Final
10             1.0            1.0               Group A
11             2.0            0.0               Group A
..             ...            ...                   ...
565            1.0            0.0        Quarter-finals
566            1.0            1.0           Semi-finals
567            2.0            0.0           Semi-finals
568            1.0            0.0  Third place play-off
569            1.0            2.0                 Final

                                  SpecialWinConditions  \
1    Ethiopia  wins due to disqualification of othe...
8                                                  NaN
9                                win after extra time
10                                                 NaN
11                                                 NaN
..                                                 ...
565                                                NaN
566                        Egypt win on Penalities 3-4
567                                                NaN
568                                                NaN
569                                                NaN

                    Stadium          City  Attendance
1                       NaN           NaN         NaN
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
10     Accra Sports Stadium         Accra         NaN
11     Accra Sports Stadium         Accra         NaN
..                      ...           ...         ...
565    Stade de Port-Gentil   Port-Gentil         NaN
566       Stade de l'Amitié    Libreville         NaN
567    Stade de Franceville   Franceville         NaN
568    Stade de Port-Gentil   Port-Gentil         NaN
569       Stade de l'Amitié    Libreville         NaN

[100 rows x 12 columns]

In [12]:
#7.Write a Pandas program to select the rows where the ‘HomeTeamGoals’ are between 3 and 6 inclusive.

df['HomeTeamGoals'] = pd.to_numeric(df['HomeTeamGoals'], errors='coerce')
selected_rows = df[(df['HomeTeamGoals'] >= 3) & (df['HomeTeamGoals'] <= 6)]
print(selected_rows)

     Year                         Date   Time    HomeTeam     AwayTeam  \
2    1957                     16-Feb-57    NaN     Egypt      Ethiopia
3    1959                     22-May-59    NaN      Egypt     Ethiopia
6    1962                     14-Jan-62    NaN  Ethiopia       Tunisia
8    1962                     20-Jan-62    NaN   Tunisia        Uganda
9    1962                     21-Jan-62    NaN  Ethiopia         Egypt
..    ...                           ...    ...        ...          ...
553  2017  20 January 2017 (2017-01-20)  20:00   Morocco          Togo
585  2019     27 June 2019 (2019-06-27)  22:00     Kenya      Tanzania
595  2019     24 June 2019 (2019-06-24)  22:00      Mali    Mauritania
608  2019      6 July 2019 (2019-07-06)  18:00   Nigeria      Cameroon
611  2019      7 July 2019 (2019-07-07)  21:00   Algeria        Guinea

     HomeTeamGoals  AwayTeamGoals              Stage    SpecialWinConditions  \
2              4.0            0.0              Final                     NaN
3              4.0            0.0   Final Tournament                     NaN
6              4.0            2.0         Semifinals                     NaN
8              3.0            0.0  Third place match                     NaN
9              4.0            2.0              Final   win after extra time
..             ...            ...                ...                     ...
553            3.0            1.0            Group C                     NaN
585            3.0            2.0            Group C                     NaN
595            4.0            1.0            Group E                     NaN
608            3.0            2.0        Round of 16                     NaN
611            3.0            0.0        Round of 16                     NaN

                    Stadium          City  Attendance
2         Municipal Stadium      Khartoum     30000.0
3     Prince Farouk Stadium         Cairo     30000.0
6    Hailé Sélassié Stadium   Addis Ababa     30000.0
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
..                      ...           ...         ...
553            Stade d'Oyem          Oyem         NaN
585         30 June Stadium         Cairo      7233.0
595            Suez Stadium          Suez      6202.0
608      Alexandria Stadium    Alexandria     10000.0
611         30 June Stadium         Cairo      8205.0

[138 rows x 12 columns]

In [13]:
#8.Write a Pandas program to change the “AwayTeamGoals” in the 3rd row to 10.
df.loc[2, 'AwayTeamGoals'] = 10
print(df)

     Year                      Date   Time      HomeTeam       AwayTeam  \
0    1957                  10-Feb-57    NaN       Sudan           Egypt
1    1957                  10-Feb-57    NaN    Ethiopia    South Africa
2    1957                  16-Feb-57    NaN       Egypt        Ethiopia
3    1959                  22-May-59    NaN        Egypt       Ethiopia
4    1959                  25-May-59    NaN       Sudan        Ethiopia
..    ...                        ...    ...          ...            ...
617  2019  11 July 2019 (2019-07-11)  21:00  Madagascar         Tunisia
618  2019  14 July 2019 (2019-07-14)  18:00     Senegal         Tunisia
619  2019  14 July 2019 (2019-07-14)  21:00     Algeria         Nigeria
620  2019  17 July 2019 (2019-07-17)  21:00     Tunisia         Nigeria
621  2019  19 July 2019 (2019-07-19)  21:00     Senegal         Algeria

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
617            0.0            3.0        Quarter-finals
618            1.0            0.0           Semi-finals
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
617                                                NaN
618                              win after extra time
619                                                NaN
620                                                NaN
621                                                NaN

                         Stadium       City  Attendance
0              Municipal Stadium   Khartoum     30000.0
1                            NaN        NaN         NaN
2              Municipal Stadium   Khartoum     30000.0
3          Prince Farouk Stadium      Cairo     30000.0
4          Prince Farouk Stadium      Cairo     20000.0
..                           ...        ...         ...
617             Al Salam Stadium      Cairo      7568.0
618              30 June Stadium      Cairo      9143.0
619  Cairo International Stadium      Cairo     49775.0
620             Al Salam Stadium      Cairo      6340.0
621  Cairo International Stadium      Cairo     75000.0

[622 rows x 12 columns]

In [14]:
#9.Write a Pandas program to sort the DataFrame first by ‘HomeTeam’ in ascending order, then by ‘HomeTeamScores’
# in descending order.
sorted_df = df.sort_values(by=['HomeTeam', 'HomeTeamGoals'], ascending=[True, False])
print(sorted_df)

     Year                         Date           Time    HomeTeam  \
205  1990                      2-Mar-90            NaN   Algeria
29   1968                     14-Jan-68            NaN   Algeria
135  1980                     16-Mar-80            NaN   Algeria
164  1984                      5-Mar-84            NaN   Algeria
171  1984                     17-Mar-84            NaN   Algeria
..    ...                           ...            ...        ...
521  2012                     12-Feb-12  20:30[note 1]    Zambia
549  2017  23 January 2017 (2017-01-23)          20:00  Zimbabwe
398  2004                     25-Jan-04          16:30  Zimbabwe
437  2006                     23-Jan-06          20:00  Zimbabwe
575  2019     30 June 2019 (2019-06-30)          21:00  Zimbabwe

         AwayTeam  HomeTeamGoals  AwayTeamGoals              Stage  \
205       Nigeria            5.0            1.0            Group A
29         Uganda            4.0            0.0            Group A
135        Guinea            3.0            2.0            Group B
164        Malawi            3.0            0.0            Group B
171         Egypt            3.0            1.0  Third place match
..            ...            ...            ...                ...
521   Ivory Coast            0.0            0.0              Final
549       Tunisia            2.0            4.0            Group B
398         Egypt            1.0            2.0            Group C
437       Senegal            0.0            2.0            Group D
575      DR Congo            0.0            4.0            Group A

              SpecialWinConditions                       Stadium  \
205                            NaN          Stade 5 Juillet 1962
29                             NaN        Hailé Sélassié Stadium
135                            NaN               Liberty Stadium
164                            NaN                  Stade Bouaké
171                            NaN  Stade Félix Houphouët-Boigny
..                             ...                           ...
521  Zambia  win on Penalities 8-7              Stade d'Angondjé
549                            NaN             Stade de l'Amitié
398                            NaN          Stade Taïeb El Mhiri
437                            NaN             Port Said Stadium
575                            NaN               30 June Stadium

             City  Attendance
205       Algiers     85000.0
29    Addis Ababa     25000.0
135        Ibadan     20000.0
164        Bouaké     10000.0
171       Abidjan       500.0
..            ...         ...
521    Libreville     40000.0
549    Libreville         NaN
398          Sfax     22000.0
437     Port Said     15000.0
575         Cairo      4364.0

[622 rows x 12 columns]

In [15]:
#10.Write a Pandas program to get list from DataFrame column headers.
column_headers = df.columns.tolist()
print(column_headers)

['Year', 'Date ', 'Time ', 'HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals', 'Stage', 'SpecialWinConditions', 'Stadium', 'City', 'Attendance']

In [16]:
#11.Write a Pandas program to append a column of your choice to your DataFrame.
import pandas as pd

# Creating a sample DataFrame
cup = pd.DataFrame({
    'HomeTeam': ['Team A', 'Team B', 'Team C', 'Team D'],
    'HomeTeamGoals': [2, 3, 1, 4],
})

# Creating a list of Away team countries
away_teams = ['France', 'Germany', 'Spain', 'Brazil']

# Appending the 'AwayTeam' column to the DataFrame
cup['AwayTeam'] = away_teams

# Displaying the updated DataFrame
print(cup)

  HomeTeam  HomeTeamGoals AwayTeam
0   Team A              2   France
1   Team B              3  Germany
2   Team C              1    Spain
3   Team D              4   Brazil

In [17]:
#12.Write a Pandas program to add 2 rows to your DataFrame.
import pandas as pd

# Create a DataFrame 'cup' with some initial data
df = pd.DataFrame({
    'HomeTeam': ['Team X', 'Team Y'],
    'AwayTeam': ['Team Z', 'Team W'],
    'HomeTeamGoals': [3, 1],
    'AwayTeamGoals': [2, 0]
})

# Define new rows to be added
new_rows = [{'HomeTeam': 'Team A', 'AwayTeam': 'Team B', 'HomeTeamGoals': 2, 'AwayTeamGoals': 1},
            {'HomeTeam': 'Team C', 'AwayTeam': 'Team D', 'HomeTeamGoals': 0, 'AwayTeamGoals': 2}]

# Append the new rows to the DataFrame
df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)

# Print the updated DataFrame
print(df)

  HomeTeam AwayTeam  HomeTeamGoals  AwayTeamGoals
0   Team X   Team Z              3              2
1   Team Y   Team W              1              0
2   Team A   Team B              2              1
3   Team C   Team D              0              2

In [18]:
#13.Write a Pandas program to change the country ‘Uganda’ to ‘China’ in the ‘AwayTeam’ column of the DataFrame.
df.loc[df['AwayTeam'] == 'Uganda', 'AwayTeam'] = 'China'
print(df)

  HomeTeam AwayTeam  HomeTeamGoals  AwayTeamGoals
0   Team X   Team Z              3              2
1   Team Y   Team W              1              0
2   Team A   Team B              2              1
3   Team C   Team D              0              2

In [19]:
#14.Write a Pandas program to reset index in your DataFrame.
df = df.reset_index(drop=True)
print(df)

  HomeTeam AwayTeam  HomeTeamGoals  AwayTeamGoals
0   Team X   Team Z              3              2
1   Team Y   Team W              1              0
2   Team A   Team B              2              1
3   Team C   Team D              0              2

#15.Write a Pandas program to check whether the ‘Stadium’ column is present in your DataFrame or not.

In [20]:

import pandas as pd

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')
if 'Stadium' in df.columns:
    print("The 'Stadium' column is present.")
else:
    print("The 'Stadium' column is not present.")

The 'Stadium' column is present.

#16.Write a Pandas program to convert the datatype of the ‘AwayTeamGoals’. (int to float)

In [21]:

import pandas as pd

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')
df['AwayTeamGoals'] = df['AwayTeamGoals'].astype(float)
print(df.dtypes)

Year                      int64
Date                     object
Time                     object
HomeTeam                 object
AwayTeam                 object
HomeTeamGoals           float64
AwayTeamGoals           float64
Stage                    object
SpecialWinConditions     object
Stadium                  object
City                     object
Attendance              float64
dtype: object

In [22]:
#17.Write a Pandas program to remove the last 10 rows from your DataFrame.
import pandas as pd

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')
df = df[:-10]
print(df)

     Year                     Date   Time      HomeTeam       AwayTeam  \
0    1957                 10-Feb-57    NaN       Sudan           Egypt
1    1957                 10-Feb-57    NaN    Ethiopia    South Africa
2    1957                 16-Feb-57    NaN       Egypt        Ethiopia
3    1959                 22-May-59    NaN        Egypt       Ethiopia
4    1959                 25-May-59    NaN       Sudan        Ethiopia
..    ...                       ...    ...          ...            ...
607  2019  5 July 2019 (2019-07-05)  21:00      Uganda         Senegal
608  2019  6 July 2019 (2019-07-06)  18:00     Nigeria        Cameroon
609  2019  6 July 2019 (2019-07-06)  21:00       Egypt    South Africa
610  2019  7 July 2019 (2019-07-07)  18:00  Madagascar        DR Congo
611  2019  7 July 2019 (2019-07-07)  21:00     Algeria          Guinea

     HomeTeamGoals  AwayTeamGoals             Stage  \
0              1.0            2.0        Semifinals
1              NaN            NaN        Semifinals
2              4.0            0.0             Final
3              4.0            0.0  Final Tournament
4              1.0            0.0  Final Tournament
..             ...            ...               ...
607            0.0            1.0       Round of 16
608            3.0            2.0       Round of 16
609            0.0            1.0       Round of 16
610            2.0            2.0       Round of 16
611            3.0            0.0       Round of 16

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
607                                                NaN
608                                                NaN
609                                                NaN
610                  Madagascar  win on Penalities 4-2
611                                                NaN

                         Stadium         City  Attendance
0              Municipal Stadium     Khartoum     30000.0
1                            NaN          NaN         NaN
2              Municipal Stadium     Khartoum     30000.0
3          Prince Farouk Stadium        Cairo     30000.0
4          Prince Farouk Stadium        Cairo     20000.0
..                           ...          ...         ...
607  Cairo International Stadium        Cairo      6950.0
608           Alexandria Stadium   Alexandria     10000.0
609  Cairo International Stadium        Cairo     75000.0
610           Alexandria Stadium   Alexandria      5890.0
611              30 June Stadium        Cairo      8205.0

[612 rows x 12 columns]

In [23]:
#18.Write a Pandas program to iterate over rows in your DataFrame.
import pandas as pd

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')
for index, row in df.iterrows():
    print(row['HomeTeam'], row['AwayTeam'])

Sudan   Egypt
Ethiopia   South Africa
Egypt   Ethiopia
Egypt  Ethiopia
Sudan   Ethiopia
Egypt  Sudan
Ethiopia   Tunisia
Egypt  Uganda
Tunisia   Uganda
Ethiopia  Egypt
Ghana   Tunisia
Ghana   Ethiopia
Ethiopia   Tunisia
Egypt  Nigeria
Egypt  Sudan
Sudan   Nigeria
Egypt  Ethiopia
Ghana   Sudan
Tunisia   Ethiopia
Senegal   Tunisia
Senegal   Ethiopia
Ghana   Congo-Léopoldville
Ivory Coast   Congo-Léopoldville
Ghana   Ivory Coast
Senegal   Ivory Coast
Ghana   Tunisia
Ethiopia   Uganda
Ivory Coast   Algeria
Ethiopia   Ivory Coast
Algeria   Uganda
Ivory Coast   Uganda
Ethiopia   Algeria
Ghana   Senegal
Congo-Kinshasa   Congo-Brazzaville
Senegal   Congo-Brazzaville
Ghana   Congo-Kinshasa
Congo-Kinshasa   Senegal
Ghana   Congo-Brazzaville
Ethiopia   Congo-Kinshasa
Ghana   Ivory Coast
Ivory Coast   Ethiopia
Congo-Kinshasa   Ghana
Cameroon   Ivory Coast
Sudan   Ethiopia
Cameroon   Ethiopia
Ivory Coast   Sudan
Ivory Coast   Ethiopia
Sudan   Cameroon
Ghana   Congo-Kinshasa
United Arab Rep.   Guinea
Congo-Kinshasa   Guinea
United Arab Rep.   Ghana
Guinea   Ghana
United Arab Rep.   Congo-Kinshasa
Ivory Coast   Ghana
United Arab Rep.   Sudan
United Arab Rep.   Ivory Coast
Sudan   Ghana
Cameroon   Kenya
Mali   Togo
Mali   Kenya
Cameroon   Togo
Togo   Kenya
Cameroon   Mali
Congo   Morocco
Zaire   Sudan
Morocco   Sudan
Zaire   Congo
Morocco   Zaire
Congo   Sudan
Cameroon   Congo
Zaire   Mali
Cameroon   Zaire
Congo   Mali
Egypt   Uganda
Zambia   Ivory Coast
Egypt   Zambia
Ivory Coast   Uganda
Egypt   Ivory Coast
Zambia   Uganda
Zaire   Guinea
Congo   Mauritius
Guinea   Mauritius
Congo   Zaire
Congo   Guinea
Zaire   Mauritius
Egypt   Zaire
Congo   Zambia
Congo   Egypt
Zaire   Zambia
Zaire   Zambia
Ethiopia   Uganda
Egypt   Guinea
Egypt   Uganda
Ethiopia   Guinea
Guinea   Uganda
Ethiopia   Egypt
Nigeria   Zaire
Morocco   Sudan
Nigeria   Sudan
Morocco   Zaire
Morocco   Nigeria
Zaire   Sudan
Guinea   Nigeria
Morocco   Egypt
Morocco   Nigeria
Guinea   Egypt
Nigeria   Egypt
Guinea   Morocco
Ghana   Zambia
Nigeria   Upper Volta
Zambia   Upper Volta
Nigeria   Ghana
Zambia   Nigeria
Ghana   Upper Volta
Morocco   Tunisia
Uganda   Congo
Tunisia   Uganda
Morocco   Congo
Congo   Tunisia
Uganda   Morocco
Ghana   Tunisia
Uganda   Nigeria
Nigeria   Tunisia
Ghana   Uganda
Nigeria   Tanzania
Egypt   Ivory Coast
Egypt   Tanzania
Nigeria   Ivory Coast
Ivory Coast   Tanzania
Nigeria   Egypt
Ghana   Algeria
Morocco   Guinea
Algeria   Morocco
Ghana   Guinea
Algeria   Guinea
Morocco   Ghana
Nigeria   Morocco
Algeria   Egypt
Morocco   Egypt
Nigeria   Algeria
Libya   Ghana
Cameroon   Tunisia
Cameroon   Ghana
Libya   Tunisia
Ghana   Tunisia
Libya   Cameroon
Nigeria   Ethiopia
Algeria   Zambia
Zambia   Ethiopia
Algeria   Nigeria
Algeria   Ethiopia
Zambia   Nigeria
Ghana   Algeria
Libya   Zambia
Zambia   Algeria
Ghana   Libya
Ivory Coast   Togo
Egypt   Cameroon
Cameroon   Togo
Ivory Coast   Egypt
Egypt   Togo
Ivory Coast   Cameroon
Ghana   Nigeria
Algeria   Malawi
Malawi   Nigeria
Algeria   Ghana
Algeria   Nigeria
Ghana   Malawi
Egypt   Nigeria
Algeria   Cameroon
Algeria   Egypt
Cameroon   Nigeria
Senegal   Egypt
Ivory Coast   Mozambique
Senegal   Mozambique
Egypt   Ivory Coast
Ivory Coast   Senegal
Egypt   Mozambique
Algeria   Morocco
Cameroon   Zambia
Algeria   Zambia
Cameroon   Morocco
Morocco   Zambia
Cameroon   Algeria
Cameroon   Ivory Coast
Egypt   Morocco
Ivory Coast   Morocco
Egypt   Cameroon
Morocco   Zaire
Ivory Coast   Algeria
Ivory Coast   Zaire
Morocco   Algeria
Algeria   Zaire
Morocco   Ivory Coast
Cameroon   Egypt
Nigeria   Kenya
Cameroon   Nigeria
Egypt   Kenya
Cameroon   Kenya
Nigeria   Egypt
Nigeria   Algeria
Morocco   Cameroon
Morocco   Algeria
Cameroon   Nigeria
Algeria   Nigeria
Ivory Coast   Egypt
Nigeria   Egypt
Algeria   Ivory Coast
Nigeria   Ivory Coast
Algeria   Egypt
Zambia   Cameroon
Senegal   Kenya
Zambia   Kenya
Senegal   Cameroon
Zambia   Senegal
Cameroon   Kenya
Zambia   Nigeria
Algeria   Senegal
Zambia   Senegal
Algeria   Nigeria
Nigeria   Senegal
Nigeria   Kenya
Senegal   Kenya
Cameroon   Morocco
Morocco   Zaire
Cameroon   Zaire
Ivory Coast   Algeria
Ivory Coast   Congo
Algeria   Congo
Zambia   Egypt
Ghana   Zambia
Ghana   Egypt
Nigeria   Zaire
Cameroon   Senegal
Ivory Coast   Zambia
Ghana   Congo
Ghana   Nigeria
Cameroon   Ivory Coast
Nigeria   Cameroon
Ivory Coast   Ghana
Tunisia   Mali
Mali   Zaire
Tunisia   Zaire
Nigeria   Gabon
Egypt   Gabon
Nigeria   Egypt
Ivory Coast   Sierra Leone
Zambia   Sierra Leone
Zambia   Ivory Coast
Ghana   Guinea
Senegal   Guinea
Ghana   Senegal
Zaire   Nigeria
Egypt   Mali
Zambia   Senegal
Ghana   Ivory Coast
Nigeria   Ivory Coast
Zambia   Mali
Ivory Coast   Mali
Nigeria   Zambia
South Africa   Cameroon
Egypt   Angola
Cameroon   Egypt
South Africa   Angola
South Africa   Egypt
Angola   Cameroon
Zambia   Algeria
Sierra Leone   Burkina Faso
Algeria   Sierra Leone
Zambia   Burkina Faso
Algeria   Burkina Faso
Zambia   Sierra Leone
Gabon   Liberia
Gabon   Zaire
Zaire   Liberia
Ghana   Ivory Coast
Tunisia   Mozambique
Ghana   Tunisia
Ivory Coast   Mozambique
Tunisia   Ivory Coast
Ghana   Mozambique
South Africa   Algeria
Zambia   Egypt
Gabon   Tunisia
Ghana   Zaire
South Africa   Ghana
Zambia   Tunisia
Ghana   Zambia
South Africa   Tunisia
Burkina Faso   Cameroon
Algeria   Guinea
Cameroon   Guinea
Burkina Faso   Algeria
Burkina Faso   Guinea
Cameroon   Algeria
DR Congo   Togo
Ghana   Tunisia
Tunisia   DR Congo
Togo   Ghana
DR Congo   Ghana
Tunisia   Togo
South Africa   Angola
Ivory Coast   Namibia
Ivory Coast   South Africa
Angola   Namibia
Ivory Coast   Angola
South Africa   Namibia
Morocco   Zambia
Egypt   Mozambique
Egypt   Zambia
Morocco   Mozambique
Zambia   Mozambique
Morocco   Egypt
Cameroon   DR Congo
Tunisia   Burkina Faso
Ivory Coast   Egypt
Morocco   South Africa
DR Congo   South Africa
Burkina Faso   Egypt
DR Congo   Burkina Faso
South Africa   Egypt
Ghana   Cameroon
Ivory Coast   Togo
Ghana   Togo
Cameroon   Ivory Coast
Ghana   Ivory Coast
Cameroon   Togo
South Africa   Gabon
DR Congo   Algeria
South Africa   DR Congo
Algeria   Gabon
South Africa   Algeria
DR Congo   Gabon
Egypt   Zambia
Burkina Faso   Senegal
Egypt   Senegal
Zambia   Burkina Faso
Egypt   Burkina Faso
Zambia   Senegal
Nigeria   Tunisia
Morocco   Congo
Nigeria   Congo
Tunisia   Morocco
Nigeria   Morocco
Tunisia   Congo
Cameroon   Algeria
South Africa   Ghana
Egypt   Tunisia
Nigeria   Senegal
Nigeria   South Africa
Cameroon   Tunisia
South Africa   Tunisia
Nigeria   Cameroon
Mali   Liberia
Algeria   Nigeria
Mali   Nigeria
Liberia   Algeria
Mali   Algeria
Liberia   Nigeria
South Africa   Burkina Faso
Morocco   Ghana
South Africa   Ghana
Burkina Faso   Morocco
South Africa   Morocco
Burkina Faso   Ghana
Cameroon   DR Congo
Togo   Ivory Coast
Cameroon   Ivory Coast
DR Congo   Togo
Cameroon   Togo
DR Congo   Ivory Coast
Egypt   Senegal
Zambia   Tunisia
Egypt   Tunisia
Senegal   Zambia
Egypt   Zambia
Senegal   Tunisia
South Africa   Mali
Nigeria   Ghana
Cameroon   Egypt
Senegal   DR Congo
Nigeria   Senegal
Mali   Cameroon
Nigeria   Mali
Senegal   Cameroon
Tunisia   Rwanda
DR Congo   Guinea
Rwanda   Guinea
Tunisia   DR Congo
Tunisia   Guinea
Rwanda   DR Congo
Kenya   Mali
Senegal   Burkina Faso
Senegal   Kenya
Burkina Faso   Mali
Senegal   Mali
Burkina Faso   Kenya
Zimbabwe   Egypt
Cameroon   Algeria
Cameroon   Zimbabwe
Algeria   Egypt
Cameroon   Egypt
Algeria   Zimbabwe
Nigeria   Morocco
South Africa   Benin
Nigeria   South Africa
Morocco   Benin
Morocco   South Africa
Nigeria   Benin
Mali   Guinea
Tunisia   Senegal
Cameroon   Nigeria
Morocco   Algeria
Tunisia   Nigeria
Morocco   Mali
Nigeria   Mali
Tunisia   Morocco
Egypt   Libya
Morocco   Ivory Coast
Libya   Ivory Coast
Egypt   Morocco
Egypt   Ivory Coast
Libya   Morocco
Cameroon   Angola
Togo   DR Congo
Angola   DR Congo
Cameroon   Togo
Angola   Togo
Cameroon   DR Congo
Tunisia   Zambia
South Africa   Guinea
Zambia   Guinea
Tunisia   South Africa
Tunisia   Guinea
Zambia   South Africa
Nigeria   Ghana
Zimbabwe   Senegal
Ghana   Senegal
Nigeria   Zimbabwe
Nigeria   Senegal
Ghana   Zimbabwe
Guinea   Senegal
Egypt   DR Congo
Nigeria   Tunisia
Cameroon   Ivory Coast
Egypt   Senegal
Nigeria   Ivory Coast
Senegal   Nigeria
Egypt   Ivory Coast
Ghana   Guinea
Namibia   Morocco
Guinea   Morocco
Ghana   Namibia
Ghana   Morocco
Guinea   Namibia
Nigeria   Ivory Coast
Mali   Benin
Ivory Coast   Benin
Nigeria   Mali
Nigeria   Benin
Ivory Coast   Mali
Egypt   Cameroon
Sudan   Zambia
Cameroon   Zambia
Egypt   Sudan
Cameroon   Sudan
Egypt   Zambia
Tunisia   Senegal
South Africa   Angola
Senegal   Angola
Tunisia   South Africa
Senegal   South Africa
Tunisia   Angola
Ghana   Nigeria
Ivory Coast   Guinea
Egypt   Angola
Tunisia   Cameroon
Ghana   Cameroon
Ivory Coast   Egypt
Ghana   Ivory Coast
Cameroon   Egypt
Angola   Mali
Malawi   Algeria
Mali   Algeria
Angola   Malawi
Angola   Algeria
Mali   Malawi
Ivory Coast   Burkina Faso
Ghana   Togo
Burkina Faso   Togo
Ivory Coast   Ghana
Burkina Faso   Ghana
Ivory Coast   Togo
Egypt   Nigeria
Mozambique   Benin
Nigeria   Benin
Egypt   Mozambique
Egypt   Benin
Nigeria   Mozambique
Cameroon   Gabon
Zambia   Tunisia
Gabon   Tunisia
Cameroon   Zambia
Gabon   Zambia
Cameroon   Tunisia
Angola   Ghana
Ivory Coast   Algeria
Egypt   Cameroon
Zambia   Nigeria
Ghana   Nigeria
Algeria   Egypt
Nigeria   Algeria
Ghana   Egypt
Zambia   Sudan
Ivory Coast   Equatorial Guinea
Gabon   Mali
Ghana   Tunisia
Zambia   Ghana
Mali   Ivory Coast
Ghana   Mali
Zambia   Ivory Coast
Ghana   Cape Verde
South Africa   Mali
Ivory Coast   Nigeria
Burkina Faso   Togo
Mali   Nigeria
Burkina Faso   Ghana
Mali   Ghana
Nigeria   Burkina Faso
Congo   DR Congo
Tunisia   Equatorial Guinea
Ghana   Guinea
Ivory Coast   Algeria
DR Congo   Ivory Coast
Ghana   Equatorial Guinea
DR Congo   Equatorial Guinea
Ivory Coast   Ghana
Gabon   Guinea-Bissau
Burkina Faso   Cameroon
Gabon   Burkina Faso
Cameroon   Guinea-Bissau
Cameroon   Gabon
Guinea-Bissau   Burkina Faso
Algeria   Zimbabwe
Tunisia   Senegal
Algeria   Tunisia
Senegal   Zimbabwe
Senegal   Algeria
Zimbabwe   Tunisia
Ivory Coast   Togo
DR Congo   Morocco
Ivory Coast   DR Congo
Morocco   Togo
Morocco   Ivory Coast
Togo   DR Congo
Ghana   Uganda
Mali   Egypt
Ghana   Mali
Egypt   Uganda
Egypt   Ghana
Uganda   Mali
Burkina Faso   Tunisia
Senegal   Cameroon
DR Congo   Ghana
Egypt   Morocco
Burkina Faso   Egypt
Cameroon   Ghana
Burkina Faso   Ghana
Egypt   Cameroon
Egypt   Zimbabwe
DR Congo   Uganda
Uganda   Zimbabwe
Egypt   DR Congo
Uganda   Egypt
Zimbabwe   DR Congo
Nigeria   Burundi
Guinea   Madagascar
Nigeria   Guinea
Madagascar   Burundi
Madagascar   Nigeria
Burundi   Guinea
Senegal   Tanzania
Algeria   Kenya
Senegal   Algeria
Kenya   Tanzania
Kenya   Senegal
Tanzania   Algeria
Morocco   Namibia
Ivory Coast   South Africa
Morocco   Ivory Coast
South Africa   Namibia
South Africa   Morocco
Namibia   Ivory Coast
Tunisia   Angola
Mali   Mauritania
Tunisia   Mali
Mauritania   Angola
Mauritania   Tunisia
Angola   Mali
Cameroon   Guinea-Bissau
Ghana   Benin
Cameroon   Ghana
Benin   Guinea-Bissau
Benin   Cameroon
Guinea-Bissau   Ghana
Morocco   Benin
Uganda   Senegal
Nigeria   Cameroon
Egypt   South Africa
Madagascar   DR Congo
Algeria   Guinea
Mali   Ivory Coast
Ghana   Tunisia
Senegal   Benin
Nigeria   South Africa
Ivory Coast   Algeria
Madagascar   Tunisia
Senegal   Tunisia
Algeria   Nigeria
Tunisia   Nigeria
Senegal   Algeria

In [24]:
#19.Write a Pandas program to change the order of your DataFrame columns.
import pandas as pd

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')
new_column_order = ['AwayTeam', 'AwayTeamGoals', 'HomeTeam', 'HomeTeamGoals']
df = df[new_column_order]
print(df)

          AwayTeam  AwayTeamGoals     HomeTeam  HomeTeamGoals
0            Egypt            2.0       Sudan             1.0
1     South Africa            NaN    Ethiopia             NaN
2         Ethiopia            0.0       Egypt             4.0
3         Ethiopia            0.0        Egypt            4.0
4         Ethiopia            0.0       Sudan             1.0
..             ...            ...          ...            ...
617        Tunisia            3.0  Madagascar             0.0
618        Tunisia            0.0     Senegal             1.0
619        Nigeria            1.0     Algeria             2.0
620        Nigeria            1.0     Tunisia             0.0
621        Algeria            1.0     Senegal             0.0

[622 rows x 4 columns]

In [25]:
#20.Write a Pandas program to delete DataFrame row(s) whose value is 0 in the ‘HomeTeamGoals’ columns.
import pandas as pd

df= pd.read_csv('C:/Users/USER/Desktop/RECESS/Day/cup.csv')

# Deleting rows with HomeTeamGoals equal to 0
df= df.drop(df[df['HomeTeamGoals'] == 0].index)

# Printing the updated DataFrame
print(df)

     Year                      Date   Time       HomeTeam       AwayTeam  \
0    1957                  10-Feb-57    NaN        Sudan           Egypt
1    1957                  10-Feb-57    NaN     Ethiopia    South Africa
2    1957                  16-Feb-57    NaN        Egypt        Ethiopia
3    1959                  22-May-59    NaN         Egypt       Ethiopia
4    1959                  25-May-59    NaN        Sudan        Ethiopia
..    ...                        ...    ...           ...            ...
614  2019  10 July 2019 (2019-07-10)  18:00      Senegal           Benin
615  2019  10 July 2019 (2019-07-10)  21:00      Nigeria    South Africa
616  2019  11 July 2019 (2019-07-11)  18:00  Ivory Coast         Algeria
618  2019  14 July 2019 (2019-07-14)  18:00      Senegal         Tunisia
619  2019  14 July 2019 (2019-07-14)  21:00      Algeria         Nigeria

     HomeTeamGoals  AwayTeamGoals             Stage  \
0              1.0            2.0        Semifinals
1              NaN            NaN        Semifinals
2              4.0            0.0             Final
3              4.0            0.0  Final Tournament
4              1.0            0.0  Final Tournament
..             ...            ...               ...
614            1.0            0.0    Quarter-finals
615            2.0            1.0    Quarter-finals
616            1.0            1.0    Quarter-finals
618            1.0            0.0       Semi-finals
619            2.0            1.0       Semi-finals

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
614                                                NaN
615                                                NaN
616                      Algeria win on Penalities 3-4
618                              win after extra time
619                                                NaN

                         Stadium       City  Attendance
0              Municipal Stadium   Khartoum     30000.0
1                            NaN        NaN         NaN
2              Municipal Stadium   Khartoum     30000.0
3          Prince Farouk Stadium      Cairo     30000.0
4          Prince Farouk Stadium      Cairo     20000.0
..                           ...        ...         ...
614              30 June Stadium      Cairo      5798.0
615  Cairo International Stadium      Cairo     48343.0
616                 Suez Stadium       Suez      8233.0
618              30 June Stadium      Cairo      9143.0
619  Cairo International Stadium      Cairo     49775.0

[494 rows x 12 columns]